// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/matsuboshi/league-matrix-app/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// NewMockMatrixOperationsDomainInterface creates a new instance of MockMatrixOperationsDomainInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMatrixOperationsDomainInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMatrixOperationsDomainInterface {
	mock := &MockMatrixOperationsDomainInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMatrixOperationsDomainInterface is an autogenerated mock type for the MatrixOperationsDomainInterface type
type MockMatrixOperationsDomainInterface struct {
	mock.Mock
}

type MockMatrixOperationsDomainInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMatrixOperationsDomainInterface) EXPECT() *MockMatrixOperationsDomainInterface_Expecter {
	return &MockMatrixOperationsDomainInterface_Expecter{mock: &_m.Mock}
}

// IsValidOperation provides a mock function for the type MockMatrixOperationsDomainInterface
func (_mock *MockMatrixOperationsDomainInterface) IsValidOperation(ctx context.Context, operation string) error {
	ret := _mock.Called(ctx, operation)

	if len(ret) == 0 {
		panic("no return value specified for IsValidOperation")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, operation)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMatrixOperationsDomainInterface_IsValidOperation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsValidOperation'
type MockMatrixOperationsDomainInterface_IsValidOperation_Call struct {
	*mock.Call
}

// IsValidOperation is a helper method to define mock.On call
//   - ctx context.Context
//   - operation string
func (_e *MockMatrixOperationsDomainInterface_Expecter) IsValidOperation(ctx interface{}, operation interface{}) *MockMatrixOperationsDomainInterface_IsValidOperation_Call {
	return &MockMatrixOperationsDomainInterface_IsValidOperation_Call{Call: _e.mock.On("IsValidOperation", ctx, operation)}
}

func (_c *MockMatrixOperationsDomainInterface_IsValidOperation_Call) Run(run func(ctx context.Context, operation string)) *MockMatrixOperationsDomainInterface_IsValidOperation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMatrixOperationsDomainInterface_IsValidOperation_Call) Return(err error) *MockMatrixOperationsDomainInterface_IsValidOperation_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMatrixOperationsDomainInterface_IsValidOperation_Call) RunAndReturn(run func(ctx context.Context, operation string) error) *MockMatrixOperationsDomainInterface_IsValidOperation_Call {
	_c.Call.Return(run)
	return _c
}

// ListOperations provides a mock function for the type MockMatrixOperationsDomainInterface
func (_mock *MockMatrixOperationsDomainInterface) ListOperations() []string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ListOperations")
	}

	var r0 []string
	if returnFunc, ok := ret.Get(0).(func() []string); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	return r0
}

// MockMatrixOperationsDomainInterface_ListOperations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListOperations'
type MockMatrixOperationsDomainInterface_ListOperations_Call struct {
	*mock.Call
}

// ListOperations is a helper method to define mock.On call
func (_e *MockMatrixOperationsDomainInterface_Expecter) ListOperations() *MockMatrixOperationsDomainInterface_ListOperations_Call {
	return &MockMatrixOperationsDomainInterface_ListOperations_Call{Call: _e.mock.On("ListOperations")}
}

func (_c *MockMatrixOperationsDomainInterface_ListOperations_Call) Run(run func()) *MockMatrixOperationsDomainInterface_ListOperations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMatrixOperationsDomainInterface_ListOperations_Call) Return(strings []string) *MockMatrixOperationsDomainInterface_ListOperations_Call {
	_c.Call.Return(strings)
	return _c
}

func (_c *MockMatrixOperationsDomainInterface_ListOperations_Call) RunAndReturn(run func() []string) *MockMatrixOperationsDomainInterface_ListOperations_Call {
	_c.Call.Return(run)
	return _c
}

// RunOperation provides a mock function for the type MockMatrixOperationsDomainInterface
func (_mock *MockMatrixOperationsDomainInterface) RunOperation(ctx context.Context, matrix *entity.Matrix, operation string) (string, error) {
	ret := _mock.Called(ctx, matrix, operation)

	if len(ret) == 0 {
		panic("no return value specified for RunOperation")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Matrix, string) (string, error)); ok {
		return returnFunc(ctx, matrix, operation)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Matrix, string) string); ok {
		r0 = returnFunc(ctx, matrix, operation)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *entity.Matrix, string) error); ok {
		r1 = returnFunc(ctx, matrix, operation)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMatrixOperationsDomainInterface_RunOperation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RunOperation'
type MockMatrixOperationsDomainInterface_RunOperation_Call struct {
	*mock.Call
}

// RunOperation is a helper method to define mock.On call
//   - ctx context.Context
//   - matrix *entity.Matrix
//   - operation string
func (_e *MockMatrixOperationsDomainInterface_Expecter) RunOperation(ctx interface{}, matrix interface{}, operation interface{}) *MockMatrixOperationsDomainInterface_RunOperation_Call {
	return &MockMatrixOperationsDomainInterface_RunOperation_Call{Call: _e.mock.On("RunOperation", ctx, matrix, operation)}
}

func (_c *MockMatrixOperationsDomainInterface_RunOperation_Call) Run(run func(ctx context.Context, matrix *entity.Matrix, operation string)) *MockMatrixOperationsDomainInterface_RunOperation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entity.Matrix
		if args[1] != nil {
			arg1 = args[1].(*entity.Matrix)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockMatrixOperationsDomainInterface_RunOperation_Call) Return(s string, err error) *MockMatrixOperationsDomainInterface_RunOperation_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockMatrixOperationsDomainInterface_RunOperation_Call) RunAndReturn(run func(ctx context.Context, matrix *entity.Matrix, operation string) (string, error)) *MockMatrixOperationsDomainInterface_RunOperation_Call {
	_c.Call.Return(run)
	return _c
}
