// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/matsuboshi/league-matrix-app/internal/entity"
	"github.com/matsuboshi/league-matrix-app/internal/repository"
	mock "github.com/stretchr/testify/mock"
)

// NewMockMatrixValidatorDomainInterface creates a new instance of MockMatrixValidatorDomainInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMatrixValidatorDomainInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMatrixValidatorDomainInterface {
	mock := &MockMatrixValidatorDomainInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMatrixValidatorDomainInterface is an autogenerated mock type for the MatrixValidatorDomainInterface type
type MockMatrixValidatorDomainInterface struct {
	mock.Mock
}

type MockMatrixValidatorDomainInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMatrixValidatorDomainInterface) EXPECT() *MockMatrixValidatorDomainInterface_Expecter {
	return &MockMatrixValidatorDomainInterface_Expecter{mock: &_m.Mock}
}

// Validate provides a mock function for the type MockMatrixValidatorDomainInterface
func (_mock *MockMatrixValidatorDomainInterface) Validate(ctx context.Context, matrix *repository.MatrixFileContent) (*entity.Matrix, error) {
	ret := _mock.Called(ctx, matrix)

	if len(ret) == 0 {
		panic("no return value specified for Validate")
	}

	var r0 *entity.Matrix
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *repository.MatrixFileContent) (*entity.Matrix, error)); ok {
		return returnFunc(ctx, matrix)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *repository.MatrixFileContent) *entity.Matrix); ok {
		r0 = returnFunc(ctx, matrix)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Matrix)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *repository.MatrixFileContent) error); ok {
		r1 = returnFunc(ctx, matrix)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMatrixValidatorDomainInterface_Validate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Validate'
type MockMatrixValidatorDomainInterface_Validate_Call struct {
	*mock.Call
}

// Validate is a helper method to define mock.On call
//   - ctx context.Context
//   - matrix *repository.MatrixFileContent
func (_e *MockMatrixValidatorDomainInterface_Expecter) Validate(ctx interface{}, matrix interface{}) *MockMatrixValidatorDomainInterface_Validate_Call {
	return &MockMatrixValidatorDomainInterface_Validate_Call{Call: _e.mock.On("Validate", ctx, matrix)}
}

func (_c *MockMatrixValidatorDomainInterface_Validate_Call) Run(run func(ctx context.Context, matrix *repository.MatrixFileContent)) *MockMatrixValidatorDomainInterface_Validate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *repository.MatrixFileContent
		if args[1] != nil {
			arg1 = args[1].(*repository.MatrixFileContent)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMatrixValidatorDomainInterface_Validate_Call) Return(matrix1 *entity.Matrix, err error) *MockMatrixValidatorDomainInterface_Validate_Call {
	_c.Call.Return(matrix1, err)
	return _c
}

func (_c *MockMatrixValidatorDomainInterface_Validate_Call) RunAndReturn(run func(ctx context.Context, matrix *repository.MatrixFileContent) (*entity.Matrix, error)) *MockMatrixValidatorDomainInterface_Validate_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateFilePath provides a mock function for the type MockMatrixValidatorDomainInterface
func (_mock *MockMatrixValidatorDomainInterface) ValidateFilePath(ctx context.Context, filePath string) error {
	ret := _mock.Called(ctx, filePath)

	if len(ret) == 0 {
		panic("no return value specified for ValidateFilePath")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, filePath)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMatrixValidatorDomainInterface_ValidateFilePath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateFilePath'
type MockMatrixValidatorDomainInterface_ValidateFilePath_Call struct {
	*mock.Call
}

// ValidateFilePath is a helper method to define mock.On call
//   - ctx context.Context
//   - filePath string
func (_e *MockMatrixValidatorDomainInterface_Expecter) ValidateFilePath(ctx interface{}, filePath interface{}) *MockMatrixValidatorDomainInterface_ValidateFilePath_Call {
	return &MockMatrixValidatorDomainInterface_ValidateFilePath_Call{Call: _e.mock.On("ValidateFilePath", ctx, filePath)}
}

func (_c *MockMatrixValidatorDomainInterface_ValidateFilePath_Call) Run(run func(ctx context.Context, filePath string)) *MockMatrixValidatorDomainInterface_ValidateFilePath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMatrixValidatorDomainInterface_ValidateFilePath_Call) Return(err error) *MockMatrixValidatorDomainInterface_ValidateFilePath_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMatrixValidatorDomainInterface_ValidateFilePath_Call) RunAndReturn(run func(ctx context.Context, filePath string) error) *MockMatrixValidatorDomainInterface_ValidateFilePath_Call {
	_c.Call.Return(run)
	return _c
}
