// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/matrix_validator.go

// Package gomocks is a generated GoMock package.
package gomocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	entity "github.com/matsuboshi/league-matrix-app/internal/entity"
	repository "github.com/matsuboshi/league-matrix-app/internal/repository"
)

// MockMatrixValidatorDomainInterface is a mock of MatrixValidatorDomainInterface interface.
type MockMatrixValidatorDomainInterface struct {
	ctrl     *gomock.Controller
	recorder *MockMatrixValidatorDomainInterfaceMockRecorder
}

// MockMatrixValidatorDomainInterfaceMockRecorder is the mock recorder for MockMatrixValidatorDomainInterface.
type MockMatrixValidatorDomainInterfaceMockRecorder struct {
	mock *MockMatrixValidatorDomainInterface
}

// NewMockMatrixValidatorDomainInterface creates a new mock instance.
func NewMockMatrixValidatorDomainInterface(ctrl *gomock.Controller) *MockMatrixValidatorDomainInterface {
	mock := &MockMatrixValidatorDomainInterface{ctrl: ctrl}
	mock.recorder = &MockMatrixValidatorDomainInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMatrixValidatorDomainInterface) EXPECT() *MockMatrixValidatorDomainInterfaceMockRecorder {
	return m.recorder
}

// Validate mocks base method.
func (m *MockMatrixValidatorDomainInterface) Validate(ctx context.Context, matrix *repository.MatrixFileContent) (*entity.Matrix, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Validate", ctx, matrix)
	ret0, _ := ret[0].(*entity.Matrix)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Validate indicates an expected call of Validate.
func (mr *MockMatrixValidatorDomainInterfaceMockRecorder) Validate(ctx, matrix interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Validate", reflect.TypeOf((*MockMatrixValidatorDomainInterface)(nil).Validate), ctx, matrix)
}

// ValidateFilePath mocks base method.
func (m *MockMatrixValidatorDomainInterface) ValidateFilePath(ctx context.Context, filePath string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateFilePath", ctx, filePath)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateFilePath indicates an expected call of ValidateFilePath.
func (mr *MockMatrixValidatorDomainInterfaceMockRecorder) ValidateFilePath(ctx, filePath interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateFilePath", reflect.TypeOf((*MockMatrixValidatorDomainInterface)(nil).ValidateFilePath), ctx, filePath)
}
