// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/matrix.go

// Package gomocks is a generated GoMock package.
package gomocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockMatrixDomainInterface is a mock of MatrixDomainInterface interface.
type MockMatrixDomainInterface struct {
	ctrl     *gomock.Controller
	recorder *MockMatrixDomainInterfaceMockRecorder
}

// MockMatrixDomainInterfaceMockRecorder is the mock recorder for MockMatrixDomainInterface.
type MockMatrixDomainInterfaceMockRecorder struct {
	mock *MockMatrixDomainInterface
}

// NewMockMatrixDomainInterface creates a new mock instance.
func NewMockMatrixDomainInterface(ctrl *gomock.Controller) *MockMatrixDomainInterface {
	mock := &MockMatrixDomainInterface{ctrl: ctrl}
	mock.recorder = &MockMatrixDomainInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMatrixDomainInterface) EXPECT() *MockMatrixDomainInterfaceMockRecorder {
	return m.recorder
}

// ListMatrixOperations mocks base method.
func (m *MockMatrixDomainInterface) ListMatrixOperations() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMatrixOperations")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMatrixOperations indicates an expected call of ListMatrixOperations.
func (mr *MockMatrixDomainInterfaceMockRecorder) ListMatrixOperations() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMatrixOperations", reflect.TypeOf((*MockMatrixDomainInterface)(nil).ListMatrixOperations))
}

// ProcessMatrix mocks base method.
func (m *MockMatrixDomainInterface) ProcessMatrix(ctx context.Context, operation, filePath string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessMatrix", ctx, operation, filePath)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProcessMatrix indicates an expected call of ProcessMatrix.
func (mr *MockMatrixDomainInterfaceMockRecorder) ProcessMatrix(ctx, operation, filePath interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessMatrix", reflect.TypeOf((*MockMatrixDomainInterface)(nil).ProcessMatrix), ctx, operation, filePath)
}
