// Code generated by MockGen. DO NOT EDIT.
// Source: internal/handler/matrix.go

// Package gomocks is a generated GoMock package.
package gomocks

import (
	http "net/http"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockMatrixHandlerInterface is a mock of MatrixHandlerInterface interface.
type MockMatrixHandlerInterface struct {
	ctrl     *gomock.Controller
	recorder *MockMatrixHandlerInterfaceMockRecorder
}

// MockMatrixHandlerInterfaceMockRecorder is the mock recorder for MockMatrixHandlerInterface.
type MockMatrixHandlerInterfaceMockRecorder struct {
	mock *MockMatrixHandlerInterface
}

// NewMockMatrixHandlerInterface creates a new mock instance.
func NewMockMatrixHandlerInterface(ctrl *gomock.Controller) *MockMatrixHandlerInterface {
	mock := &MockMatrixHandlerInterface{ctrl: ctrl}
	mock.recorder = &MockMatrixHandlerInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMatrixHandlerInterface) EXPECT() *MockMatrixHandlerInterfaceMockRecorder {
	return m.recorder
}

// ListMatrixOperations mocks base method.
func (m *MockMatrixHandlerInterface) ListMatrixOperations(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ListMatrixOperations", w, r)
}

// ListMatrixOperations indicates an expected call of ListMatrixOperations.
func (mr *MockMatrixHandlerInterfaceMockRecorder) ListMatrixOperations(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMatrixOperations", reflect.TypeOf((*MockMatrixHandlerInterface)(nil).ListMatrixOperations), w, r)
}

// ProcessMatrix mocks base method.
func (m *MockMatrixHandlerInterface) ProcessMatrix(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ProcessMatrix", w, r)
}

// ProcessMatrix indicates an expected call of ProcessMatrix.
func (mr *MockMatrixHandlerInterfaceMockRecorder) ProcessMatrix(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessMatrix", reflect.TypeOf((*MockMatrixHandlerInterface)(nil).ProcessMatrix), w, r)
}
