// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package handler

import (
	"net/http"

	mock "github.com/stretchr/testify/mock"
)

// NewMockMatrixHandlerInterface creates a new instance of MockMatrixHandlerInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMatrixHandlerInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMatrixHandlerInterface {
	mock := &MockMatrixHandlerInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMatrixHandlerInterface is an autogenerated mock type for the MatrixHandlerInterface type
type MockMatrixHandlerInterface struct {
	mock.Mock
}

type MockMatrixHandlerInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMatrixHandlerInterface) EXPECT() *MockMatrixHandlerInterface_Expecter {
	return &MockMatrixHandlerInterface_Expecter{mock: &_m.Mock}
}

// HealthCheck provides a mock function for the type MockMatrixHandlerInterface
func (_mock *MockMatrixHandlerInterface) HealthCheck(w http.ResponseWriter, r *http.Request) {
	_mock.Called(w, r)
	return
}

// MockMatrixHandlerInterface_HealthCheck_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HealthCheck'
type MockMatrixHandlerInterface_HealthCheck_Call struct {
	*mock.Call
}

// HealthCheck is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *MockMatrixHandlerInterface_Expecter) HealthCheck(w interface{}, r interface{}) *MockMatrixHandlerInterface_HealthCheck_Call {
	return &MockMatrixHandlerInterface_HealthCheck_Call{Call: _e.mock.On("HealthCheck", w, r)}
}

func (_c *MockMatrixHandlerInterface_HealthCheck_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *MockMatrixHandlerInterface_HealthCheck_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMatrixHandlerInterface_HealthCheck_Call) Return() *MockMatrixHandlerInterface_HealthCheck_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockMatrixHandlerInterface_HealthCheck_Call) RunAndReturn(run func(w http.ResponseWriter, r *http.Request)) *MockMatrixHandlerInterface_HealthCheck_Call {
	_c.Run(run)
	return _c
}

// ListMatrixOperations provides a mock function for the type MockMatrixHandlerInterface
func (_mock *MockMatrixHandlerInterface) ListMatrixOperations(w http.ResponseWriter, r *http.Request) {
	_mock.Called(w, r)
	return
}

// MockMatrixHandlerInterface_ListMatrixOperations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListMatrixOperations'
type MockMatrixHandlerInterface_ListMatrixOperations_Call struct {
	*mock.Call
}

// ListMatrixOperations is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *MockMatrixHandlerInterface_Expecter) ListMatrixOperations(w interface{}, r interface{}) *MockMatrixHandlerInterface_ListMatrixOperations_Call {
	return &MockMatrixHandlerInterface_ListMatrixOperations_Call{Call: _e.mock.On("ListMatrixOperations", w, r)}
}

func (_c *MockMatrixHandlerInterface_ListMatrixOperations_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *MockMatrixHandlerInterface_ListMatrixOperations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMatrixHandlerInterface_ListMatrixOperations_Call) Return() *MockMatrixHandlerInterface_ListMatrixOperations_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockMatrixHandlerInterface_ListMatrixOperations_Call) RunAndReturn(run func(w http.ResponseWriter, r *http.Request)) *MockMatrixHandlerInterface_ListMatrixOperations_Call {
	_c.Run(run)
	return _c
}

// ProcessMatrix provides a mock function for the type MockMatrixHandlerInterface
func (_mock *MockMatrixHandlerInterface) ProcessMatrix(w http.ResponseWriter, r *http.Request) {
	_mock.Called(w, r)
	return
}

// MockMatrixHandlerInterface_ProcessMatrix_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProcessMatrix'
type MockMatrixHandlerInterface_ProcessMatrix_Call struct {
	*mock.Call
}

// ProcessMatrix is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *MockMatrixHandlerInterface_Expecter) ProcessMatrix(w interface{}, r interface{}) *MockMatrixHandlerInterface_ProcessMatrix_Call {
	return &MockMatrixHandlerInterface_ProcessMatrix_Call{Call: _e.mock.On("ProcessMatrix", w, r)}
}

func (_c *MockMatrixHandlerInterface_ProcessMatrix_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *MockMatrixHandlerInterface_ProcessMatrix_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMatrixHandlerInterface_ProcessMatrix_Call) Return() *MockMatrixHandlerInterface_ProcessMatrix_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockMatrixHandlerInterface_ProcessMatrix_Call) RunAndReturn(run func(w http.ResponseWriter, r *http.Request)) *MockMatrixHandlerInterface_ProcessMatrix_Call {
	_c.Run(run)
	return _c
}
